### ISSUE TITLE
kubeval doesn't seem to ignore comments

### ISSUE THREAD

**Issue by jbialy** [garethr/kubeval#104]
I seem to be getting failures of type `* Missing a kind key` when a yaml contains a comment:

```yaml
echo "
---
apiVersion: v1
kind: Namespace
metadata:
  name: efs-provisioner" | kubeval
The document stdin contains a valid Namespace
````

```yaml
echo "
# Define a Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: efs-provisioner" | kubeval
1 error occurred:

* Missing a kind key
```

**Comment by jbialy** [comment]
ah... https://github.com/garethr/kubeval/issues/78

Works fine with:

```yaml
echo "
---
# Define a Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: efs-provisioner" | kubeval
The document stdin contains a valid Namespace
```
