### ISSUE TITLE
Validate partial document

### ISSUE THREAD

**Issue by retr0h** [garethr/kubeval#109]
```
apiVersion: foo
kind: daemonset
metadata:
  metadata: foo
  namespace: foo
  labels:
    foo: bar
```

This daemonset is incomplete yet kubeval validates as ok.

```
[jodewey:~/git/konfig] 2 % kubeval foo.yaml
The document foo.yaml contains a valid DaemonSet
[jodewey:~/git/konfig] % kubectl apply --dry-run --validate -f foo.yaml
daemonset.apps "foo" created (dry run)
[jodewey:~/git/konfig] % cat foo.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: foo
  namespace: foo
```

I would expect kubeval to report an issue, esp when not fully complete.  I understand the data is valid for an update but not an initial deployment.
