### ISSUE TITLE
Provide examples of using kubeval in CI

### ISSUE THREAD

**Issue by garethr** [garethr/kubeval#11]
`kubeval` can be used to validate config files in a CI system, it would be useful to provide an example of this for different tools:

- [x] Travis example
- [ ] Ksonnet example
- [x] Helm example

**Comment by elblivion** [comment]
Hi @garethr , we are testing this in Circle CI 2.0 in this way.

```
      - run:
          name: Verify kubeconfigs
          command: |
            curl -sSLO https://github.com/garethr/kubeval/releases/download/0.1.2/kubeval-linux-amd64.tar.gz
            tar xzvf kubeval-linux-amd64.tar.gz
            chmod u+x bin/linux/amd64/kubeval
            find kubeconfigs -type f -regex '.*\.ya*ml' | xargs ./bin/linux/amd64/kubeval
```

**Comment by pizzarabe** [comment]
Hi,

we use kubeval with gitlab-ci now.

```
kubeval_testing:
  stage: testing
  image:  debian:wheezy-slim 
  variables: 
    KUBEVALURL: "https://github.com/garethr/kubeval/releases/download/0.2.0/kubeval-linux-amd64.tar.gz"
    
  before_script:
    - apt-get -y update && apt-get -y install curl
    - curl -L -O $KUBEVALURL && tar xvf kubeval-linux-amd64.tar.gz
  
  script: 
    - bin/linux/amd64/kubeval --version
    - bin/linux/amd64/kubeval k8s/*.yaml
```
