### ISSUE TITLE
Issue with commented out array values

### ISSUE THREAD

**Issue by elblivion** [garethr/kubeval#14]
For a Kubernetes Dashboard spec, also downloaded, the k8s API happily accepts this:

```
    spec:
      containers:
        <...>
        args:
          # Uncomment the following line to manually specify Kubernetes API server Host
          # If not specified, Dashboard will attempt to auto discover the API server and connect
          # to it. Uncomment only if the default does not work.
          # - --apiserver-host=http://my-address:port
```
Kubeval, however, doesn't like it:

```
The document ../../contentful/cf-infra-stacks/kubeconfigs/staging/us-east-1/delivery-k8s-002/kubernetes-dashboard/dashboard.yaml is not a valid Deployment
--> spec.template.spec.containers.0.args: Invalid type. Expected: array, given: null
```
