### ISSUE TITLE
Kubeval fails for validation

### ISSUE THREAD

**Issue by surajnarwade** [garethr/kubeval#18]
here is sample service file,

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: httpd
  name: INVALID-e_f
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: httpd
  type: INVALID
status:
  loadBalancer: {}
```
after running kubeval, it shows valid, but it's not

```
$ kubeval service.yml 
The document docker-compose.yml contains a valid Service
```
