### ISSUE TITLE
Improperly validates DaemonSet

### ISSUE THREAD

**Issue by rothgar** [garethr/kubeval#24]
Example
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ds
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: nginx
        name: nginx
```
kubeval verifies the yaml
```
kubeval test.yaml
The document test.yaml contains a valid DaemonSet
```
replicas is invalid for a DaemonSet
```
kubectl create -f test.yaml
error: error validating "test.yaml": error validating data: found invalid field replicas for v1beta1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

I didn't look at the code (I'm assuming it a straight forward fix) but wanted to report it in case I don't get to it.
