### ISSUE TITLE
Create a homebrew package for kubeval

### ISSUE THREAD

**Issue by garethr** [garethr/kubeval#26]
For folks on Mac it would be nice to simply install with homebrew.

**Comment by garethr** [comment]
Based on http://octavore.com/posts/2016/02/15/distributing-go-apps-os-x and https://github.com/linuxkit/homebrew-linuxkit I'm experimenting in https://github.com/garethr/homebrew-kubeval.

**Comment by garethr** [comment]
Updates to docs in #30

**Comment by ilovezfs** [comment]
@garethr https://github.com/Homebrew/homebrew-core/pull/17277. The glide file seems to be incomplete.

**Comment by garethr** [comment]
README updated with homebrew installation details https://github.com/garethr/kubeval/commit/839904ca6feb1fff4c212c2f74de23977817ed35

**Comment by garethr** [comment]
@ilovezfs I'm not sure what you mean by being incomplete here? If you have more details, or a gist of failures, that might be handy. Happy to look into if you have a problem.

**Comment by ilovezfs** [comment]
Oh I mean that the build fails following `glide install` unless I add additional resources manually. See https://github.com/Homebrew/homebrew-core/pull/17277/files. I will get you a build log.

**Comment by ilovezfs** [comment]
@garethr here is a gist showing what I mean: https://gist.github.com/ilovezfs/1f49932113a206d410d253e02c885921

That corresponds to this formula, which is how we do all the formulae that depend on glide:
```
iMac-TMP:homebrew-core joe$ cat Formula/kubeval.rb 
class Kubeval < Formula
  desc "Validates Kubernetes configuration files"
  homepage "https://github.com/garethr/kubeval"
  url "https://github.com/garethr/kubeval.git",
      :tag => "0.6.0",
      :revision => "4406f51d632038699ec49496aef233a7d7e4bffc"
  head "https://github.com/garethr/kubeval.git"

  depends_on "glide" => :build
  depends_on "go" => :build

  def install
    ENV["GOPATH"] = buildpath
    ENV["GLIDE_HOME"] = HOMEBREW_CACHE/"glide_home/#{name}"
    (buildpath/"src/github.com/garethr/kubeval/").install buildpath.children
    cd "src/github.com/garethr/kubeval" do
      system "glide", "install"
      buildtime = Utils.popen_read("date", "-u", "+%Y-%m-%d %I:%M:%S %Z")
      buildversion = Utils.popen_read("git", "describe", "--abbrev=0", "--tags")
      buildsha = Utils.popen_read("git", "rev-parse", "HEAD")
      ldflags = %W[
        -X \"github.com/garethr/kubeval/version.BuildTime=#{buildtime.chomp}\"
        -X \"github.com/garethr/kubeval/version.BuildVersion=#{buildversion.chomp}\"
        -X \"github.com/garethr/kubeval/version.BuildSHA=#{buildsha.chomp}\"
      ]
      system "go", "build", "-ldflags", ldflags.join(" "), "-o", bin/"kubeval"
      pkgshare.install "fixtures/invalid.yaml"
      prefix.install_metafiles
    end
  end

  test do
    output = pipe_output("#{bin}/kubeval", (pkgshare/"invalid.yaml").read, 1)
    assert_match "Expected: integer, given: string", output
  end
end
```

**Comment by garethr** [comment]
@ilovezfs mm, interesting. The clean builds in https://github.com/garethr/kubeval/blob/master/Dockerfile work for me, although this uses the make targets rather than go build directly. I'll take a look when I get a moment.

**Comment by ilovezfs** [comment]
@garethr thanks!

**Comment by ilovezfs** [comment]
@garethr I think the difference is that you're using `glide update`, which will pull in the extra deps, but the revisions for all the deps should be recorded in glide.lock so that they are pinned and get installed by glide install, including

github.com/fsnotify/fsnotify
github.com/hashicorp/hcl
github.com/magiconair/properties
github.com/mitchellh/mapstructure
github.com/pelletier/go-toml
github.com/spf13/afero
github.com/spf13/cast
github.com/spf13/jwalterweatherman
golang.org/x/sys
golang.org/x/text

which are missing.

**Comment by ilovezfs** [comment]
@garethr after running `glide update` here is the glide.lock:
```
hash: a8f1c32432725d048acd212267b87ac65a45259a64492371e95ff9357458098c
updated: 2017-08-29T00:14:43.488005828-07:00
imports:
- name: github.com/fatih/color
  version: 570b54cabe6b8eb0bc2dfce68d964677d63b5260
- name: github.com/fsnotify/fsnotify
  version: 4da3e2cfbabc9f751898f250b49f2439785783a1
- name: github.com/hashicorp/errwrap
  version: 7554cd9344cec97297fa6649b055a8c98c2a1e55
- name: github.com/hashicorp/go-multierror
  version: 83588e72410abfbe4df460eeb6f30841ae47d4c4
- name: github.com/hashicorp/hcl
  version: 8f6b1344a92ff8877cf24a5de9177bf7d0a2a187
  subpackages:
  - hcl/ast
  - hcl/parser
  - hcl/scanner
  - hcl/strconv
  - hcl/token
  - json/parser
  - json/scanner
  - json/token
- name: github.com/inconshreveable/mousetrap
  version: 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75
- name: github.com/magiconair/properties
  version: be5ece7dd465ab0765a9682137865547526d1dfb
- name: github.com/mattn/go-colorable
  version: 5411d3eea5978e6cdc258b30de592b60df6aba96
  repo: https://github.com/mattn/go-colorable
- name: github.com/mattn/go-isatty
  version: 57fdcb988a5c543893cc61bce354a6e24ab70022
  repo: https://github.com/mattn/go-isatty
- name: github.com/mitchellh/mapstructure
  version: d0303fe809921458f417bcf828397a65db30a7e4
- name: github.com/pelletier/go-toml
  version: 9c1b4e331f1e3d98e72600677699fbe212cd6d16
- name: github.com/spf13/afero
  version: 36f8810e2e3d7eeac4ac05b57f65690fbfba62a2
  subpackages:
  - mem
- name: github.com/spf13/cast
  version: acbeb36b902d72a7a4c18e8f3241075e7ab763e4
- name: github.com/spf13/cobra
  version: 34594c771f2c18301dc152640ad40ece28795373
- name: github.com/spf13/jwalterweatherman
  version: 0efa5202c04663c757d84f90f5219c1250baf94f
- name: github.com/spf13/pflag
  version: e57e3eeb33f795204c1ca35f56c44f83227c6e66
- name: github.com/spf13/viper
  version: 25b30aa063fc18e48662b86996252eabdcf2f0c7
- name: github.com/xeipuuv/gojsonpointer
  version: 6fe8760cad3569743d51ddbb243b26f8456742dc
- name: github.com/xeipuuv/gojsonreference
  version: e02fc20de94c78484cd5ffb007f8af96be030a45
- name: github.com/xeipuuv/gojsonschema
  version: 0c8571ac0ce161a5feb57375a9cdf148c98c0f70
- name: golang.org/x/sys
  version: e24f485414aeafb646f6fca458b0bf869c0880a1
  repo: https://go.googlesource.com/sys
  subpackages:
  - unix
- name: golang.org/x/text
  version: ac87088df8ef557f1e32cd00ed0b6fbc3f7ddafb
  subpackages:
  - transform
  - unicode/norm
- name: gopkg.in/yaml.v2
  version: 25c4ec802a7d637f88d584ab26798e94ad14c13b
testImports: []
```
The diff from the one you have checked in is

```
--- glide.lock.bad	2017-08-29 00:16:11.000000000 -0700
+++ glide.lock.good	2017-08-29 00:15:38.000000000 -0700
@@ -1,22 +1,49 @@
 hash: a8f1c32432725d048acd212267b87ac65a45259a64492371e95ff9357458098c
-updated: 2017-08-19T13:33:31.5843424+01:00
+updated: 2017-08-29T00:14:43.488005828-07:00
 imports:
 - name: github.com/fatih/color
   version: 570b54cabe6b8eb0bc2dfce68d964677d63b5260
+- name: github.com/fsnotify/fsnotify
+  version: 4da3e2cfbabc9f751898f250b49f2439785783a1
 - name: github.com/hashicorp/errwrap
   version: 7554cd9344cec97297fa6649b055a8c98c2a1e55
 - name: github.com/hashicorp/go-multierror
   version: 83588e72410abfbe4df460eeb6f30841ae47d4c4
+- name: github.com/hashicorp/hcl
+  version: 8f6b1344a92ff8877cf24a5de9177bf7d0a2a187
+  subpackages:
+  - hcl/ast
+  - hcl/parser
+  - hcl/scanner
+  - hcl/strconv
+  - hcl/token
+  - json/parser
+  - json/scanner
+  - json/token
 - name: github.com/inconshreveable/mousetrap
   version: 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75
+- name: github.com/magiconair/properties
+  version: be5ece7dd465ab0765a9682137865547526d1dfb
 - name: github.com/mattn/go-colorable
   version: 5411d3eea5978e6cdc258b30de592b60df6aba96
   repo: https://github.com/mattn/go-colorable
 - name: github.com/mattn/go-isatty
   version: 57fdcb988a5c543893cc61bce354a6e24ab70022
   repo: https://github.com/mattn/go-isatty
+- name: github.com/mitchellh/mapstructure
+  version: d0303fe809921458f417bcf828397a65db30a7e4
+- name: github.com/pelletier/go-toml
+  version: 9c1b4e331f1e3d98e72600677699fbe212cd6d16
+- name: github.com/spf13/afero
+  version: 36f8810e2e3d7eeac4ac05b57f65690fbfba62a2
+  subpackages:
+  - mem
+- name: github.com/spf13/cast
+  version: acbeb36b902d72a7a4c18e8f3241075e7ab763e4
 - name: github.com/spf13/cobra
   version: 34594c771f2c18301dc152640ad40ece28795373
+- name: github.com/spf13/jwalterweatherman
+  version: 0efa5202c04663c757d84f90f5219c1250baf94f
 - name: github.com/spf13/pflag
   version: e57e3eeb33f795204c1ca35f56c44f83227c6e66
 - name: github.com/spf13/viper
@@ -32,6 +59,11 @@
   repo: https://go.googlesource.com/sys
   subpackages:
   - unix
+- name: golang.org/x/text
+  version: ac87088df8ef557f1e32cd00ed0b6fbc3f7ddafb
+  subpackages:
+  - transform
+  - unicode/norm
 - name: gopkg.in/yaml.v2
   version: 25c4ec802a7d637f88d584ab26798e94ad14c13b
 testImports: []
```
