### ISSUE TITLE
Not catching incorrect property names

### ISSUE THREAD

**Issue by MitchLillie** [garethr/kubeval#39]
To reproduce:

1. Create a deployment.yml with the following:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rfq-explorer
spec:
  type: RollingUpdate
```

2. Run `kubeval deployment.yml`
3. `The document deployment.yml contains a valid Deployment`

Expected:
3. `---> spec.type: Unknown property.` Or something along those lines
