### ISSUE TITLE
Unable to validate due to problem loading schema from Github

### ISSUE THREAD

**Issue by Yggdrasil** [garethr/kubeval#66]
With the current latest kubeval 0.7.1 (from Homebrew) I get the following error:

```
$ kubeval example.yaml
1 error occurred:

* Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/master-standalone/issuer.json: Could not read schema from HTTP, response status is 404 Not Found
```

Checking the mentioned URL in a browser indeed returns a 404 as well.

**Comment by guusvw** [comment]
:+1: same for me

**Comment by garethr** [comment]
Could you provide the Kubernetes config file you're seeing this fail with? I don't see `issuer` as a resource type in the OpenAPI description of the API https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

**Comment by Yggdrasil** [comment]
I was trying to validate yaml for certmanager, the automated TLS certificate thing.

It was similar to this:

```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: default
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: user@example.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    http01: {}
```

Source: https://github.com/jetstack/cert-manager/blob/master/docs/user-guides/acme-http-validation.md
