### ISSUE TITLE
can not valid field name error which is the main key for deployment

### ISSUE THREAD

**Issue by jdxyw** [garethr/kubeval#69]
Hi, I make a fake yaml like below

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: lq
    load_balancer: AAA
    name: AAA
    namespace: algorithm
  name: AAA
  namespace: algorithm
**specASDUWIUE**:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      load_balancer: AAA
```

the highlight key **specASDUWIUE** should be spec. But this tool still pass the validation.
