### ISSUE TITLE
clusterRoleBinding files fail validation

### ISSUE THREAD

**Issue by iomv** [garethr/kubeval#71]
I get 
`---> apiGroup: Additional property apiGroup is not allowed`
when running
`cat "$file" | kubeval -f="$file" --strict`
on a `clusterRoleBinding.yaml` file

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin
subjects:
- kind: User
  name: user001
  apiGroup: ""
roleRef:
  # this is referring to the default ClusterRole 'cluster-admin'
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
```
